describe ABORTED as error message for CreateVolumeGroupSnapshot
container-storage-interface/spec pull request #563
Opened 2024-04-12 11:32 UTC by nixpanic

**What type of PR is this?**

Documentation enhancement for a common CreateVolumeGroupSnapshot error.

**What this PR does / why we need it**:

The `ABORTED` error code is currently not documented for CreateVolumeGroupSnapshot but is explained for CreateSnapshot.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce an API-breaking change?**:

```release-note
none
```

2024-06-18 17:37 UTC, saad-ali requested changes
Per @bswartz --
* "Not clear what expected behavior if GroupSnapshot for volume A, B, C pending and another one for group B, C, D is triggered"
* "Probably ok if there are 2 overlapping group snapshots and SP decided to return ABORTED for 2nd snapshot and let you retry." So it's probably ok not to explicitly mention this case.

Per @xing-yang: "Specified group snapshot, could mean all parameters have to be the same". 

Next step:
* Let's clarify what "specified group snapshot" means.

2024-06-18 17:37 UTC, saad-ali commented
Also, @nixpanic, please make sure you've signed the CLA.

2024-08-27 14:29 UTC, nixpanic commented
> Per @bswartz --
> 
>     * "Not clear what expected behavior if GroupSnapshot for volume A, B, C pending and another one for group B, C, D is triggered"
> 
>     * "Probably ok if there are 2 overlapping group snapshots and SP decided to return ABORTED for 2nd snapshot and let you retry." So it's probably ok not to explicitly mention this case.

If there is a conflict with the volumes that are part of the group snapshot that should be created, the `FAILED_PRECONDITION` error is more suitable to return. I do not think `ABORTED` needs to cover a case like this (too).

> Per @xing-yang: "Specified group snapshot, could mean all parameters have to be the same".

Yes, that is more suitable. This `ABORTED` error is for the `CreateVolumeGroupSnapshot` call, and is intended to match the similar error that `CreateVolume` can return.

> Next step:
> 
>     * Let's clarify what "specified group snapshot" means.

I've rephrased _specified group snapshot_ to _group snapshot with the exact same parameters_ and similar.


> Also, @nixpanic, please make sure you've signed the CLA.

This was completed with a group approval for IBM employees, sent by Brad Topol in the beginning of the month :partying_face:

2025-10-09 12:56 UTC, nixpanic commented
@bswartz or @saad-ali , is there still something to change here?

2025-10-09 18:08 UTC, bswartz commented
Oh, this old change fell off my radar. @xing-yang are you on board with this additional error?

2025-10-13 18:49 UTC, xing-yang commented
@bswartz This looks good to me.

2025-10-13 19:10 UTC, bswartz approved these changes

2026-02-09 07:38 UTC, nixpanic commented
@bswartz , this seems to be pending still. Could you let me know if there is something I need to do?

2026-02-11 14:44 UTC, merged